### PR TITLE
Added code for converting point clouds to mesh.

### PR DESCRIPTION
**Pull request by Zaverichintanoxolo**
Added code for converting point clouds to mesh.

### CODE REVIEW

**Comment by harshmunshioxolo** [comment]
Hi, this uses open3d. Does it have auto update of meshes?  Otherwise even trimesh has point to mesh functionality.
https://trimsh.org/trimesh.points.html

Any advantages of using open3D over trimesh?

**Comment by Zaverichintanoxolo** [comment]
To construct the mesh from point cloud, and for Trimesh, the link does not point to the function. Can you give exact link for the function?

**Comment by harshmunshioxolo** [comment]
The idea is to depend on lesser libraries, develop more natively if possible. If it's not possible, limit the dependencies. Can you look for alternative of open3D? Since we are using only one functionality of the entire library, it's better to write one function.

**Comment by Zaverichintanoxolo** [comment]
We use multiple functions from Open3D:
`        pcd = o3d.geometry.PointCloud()
        pcd.points = o3d.utility.Vector3dVector(vertices)    
        # pcd = o3d.io.read_point_cloud()
        pcd.estimate_normals(search_param=o3d.cpu.pybind.geometry.KDTreeSearchParamKNN(knn=100))
        # estimate radius for rolling ball
        distances = pcd.compute_nearest_neighbor_distance()
        avg_dist = np.mean(distances)
        radius = 2.5 * avg_dist   
        
        #orient the normals 
        o3d.geometry.PointCloud.orient_normals_to_align_with_direction(pcd, orientation_reference=np.array([0., 0., 1.]))
        o3d.geometry.PointCloud.orient_normals_consistent_tangent_plane(pcd, k=100)
        mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd, o3d.utility.DoubleVector([radius, radius * 2]))`

**Comment by harshmunshioxolo** [comment]
Ok but reading and writing is also supported in trimesh. Surface normal estimation too. It doesn't make sense to use two libraries which have common functionalities.

**Comment by harshmunshioxolo** [comment]
closing it for now, we might revisit it if no alternatives are found.

**Pull request closed without merging**
